package com.diquest.mapper.domain;

public class ClassicArtistSelector{

	String[] classicArtistNmList = {};
	String ClassicArtistNm="";
	
	public String getCSArtistNm(){
		return ClassicArtistNm;
	}
	public void setCSArtistNm(String ClassicArtistNm){
		this.ClassicArtistNm=ClassicArtistNm;
	}

	public String[] getCSArtistNmList(){
		return classicArtistNmList;
	}
	
	public ClassicArtistSelector(){
		this.ClassicArtistNm="루드비히반베토벤,"
				+"볼프강아마데우스모차르트,"
				+"프레데릭쇼팽,"
				+"요한세바스티안바흐,"
				+"프란츠슈베르트,"
				+"클로드드뷔시,"
				+"로버트슈만,"
				+"에릭사티,"
				+"세르게이라흐마니노프,"
				+"카미유생상스,"
				+"안토니오비발디,"
				+"표트르일리치차이코프스키,"
				+"요하네스브람스,"
				+"요한파헬벨,"
				+"프란츠리스트,"
				+"에드워드엘가,"
				+"펠릭스멘델스존,"
				+"프리츠크라이슬러,"
				+"모리스라벨,"
				+"에드바르그리그,"
				+"게오르크프리드리히헨델,"
				+"자코모푸치니,"
				+"니콜로파가니니,"
				+"주세페베르디,"
				+"구스타프말러,"
				+"안토닌드보르작,"
				+"조르주비제,"
				+"가브리엘포레,"
				+"요한슈트라우스2세,"
				+"요제프하이든,"
				+"모데스트무소르그스키,"
				+"쥘마스네,"
				+"안톤루빈스타인,"
				+"테클라바다르체프스카,"
				+"샤를구노,"
				+"이고르표도로비치스트라빈스키,"
				+"엔리케그라나도스,"
				+"막스브루흐,"
				+"도메니코스카를라티,"
				+"에두아르도디카푸아,"
				+"세르게이프로코피에프,"
				+"세자르프랑크,"
				+"프레드리히쿨라우,"
				+"자크오펜바흐,"
				+"알렉산더스크리아빈,"
				+"에드폴디니,"
				+"얀시벨리우스,"
				+"레오들리브,"
				+"요한슈트라우스1세,"
				+"조지거쉰,"
				+"이삭알베니즈,"
				+"카를마리아폰베버,"
				+"안톤브루크너,"
				+"리하르트바그너,"
				+"무치오클레멘티,"
				+"JohannSebastianBach,"
				+"WolfgangAmadeusMozart,"
				+"FredericChopin,"
				+"LudwigVanBeethoven,"
				+"ClaudeDebussy,"
				+"RobertSchumann,"
				+"ErikSatie,"
				+"SergeiRachmaninov,"
				+"FranzSchubert,"
				+"CamilleSaint-Saens,"
				+"AntonioVivaldi,"
				+"PyotrIl'yichTchaikovsky,"
				+"JohannesBrahms,"
				+"JohannPachelbel,"
				+"FranzLiszt,"
				+"EdwardElgar,"
				+"FelixMendelssohn,"
				+"FritzKreisler,"
				+"MauriceRavel,"
				+"EdvardGrieg,"
				+"GeorgeFridericHandel,"
				+"GiacomoPuccini,"
				+"NicoloPaganini,"
				+"GiuseppeVerdi,"
				+"GustavMahler,"
				+"AntoninDvorak,"
				+"GeorgesBizet,"
				+"GabrielFaure,"
				+"JohannStraussII,"
				+"FranzJosephHaydn,"
				+"ModestMussorgsky,"
				+"JulesMassenet,"
				+"AntonRubinstein,"
				+"TeklaBaranowska,"
				+"CharlesGounod,"
				+"IgorFyodorovichStravinsky,"
				+"EnriqueGranados,"
				+"MaxBruch,"
				+"DomenicoScarlatti,"
				+"EduardoDiCapua,"
				+"SergeiProkofiev,"
				+"CesarFranck,"
				+"FriedrichKuhlau,"
				+"JacquesOffenbach,"
				+"AlexanderScriabin,"
				+"EdePoldini,"
				+"JeanSibelius,"
				+"LeoDelibes,"
				+"JohannStraussI,"
				+"GeorgeGershwin,"
				+"IsaacAlbeniz,"
				+"CarlMariaVonWeber,"
				+"AntonBruckner,"
				+"RichardWagner,"
				+"MuzioClementi,"
				+"Beethoven,"
				+"Mozart,"
				+"Bach,"
				+"Chopin,"
				+"베토벤,"
				+"모차르트,"
				+"쇼팽"
				+"슈베르트,"
				+"드뷔시,"
				+"슈만,"
				+"슈베르트,"
				+"생상스,"
				+"비발디,"
				+"차이코프스키,"
				+"브람스,"
				+"멘델스존,"
				+"헨델,"
				+"하이든,"
				+"바흐";
		
		this.classicArtistNmList=ClassicArtistNm.split(",");
	}
	
}
